### ISSUE TITLE
Tagbot stopped working?

### ISSUE THREAD

**Issue by theogf** [JuliaGraphics/ColorTypes.jl#287]
It looks like version 0.11.2 to 0.11.4 were not correctly tagged?

**Comment by johnnychen94** [comment]
Weird, I don't have admin permission to this repo, so maybe @timholy or @SimonDanisch can help take a look.

**Comment by johnnychen94** [comment]
Just manually made the releases.

**Comment by kimikage** [comment]
The problem does not seem to be resolved.
https://github.com/JuliaGraphics/ColorTypes.jl/actions/runs/8580900779
> 2024-04-06T11:49:18.8221013Z Processing version v0.11.5 (465277a63829fbddfd9843336ef115751d5dae59)
> 2024-04-06T11:49:18.9422853Z Generating changelog for version v0.11.5 (465277a63829fbddfd9843336ef115751d5dae59)
> 2024-04-06T11:49:23.0956857Z git@github.com: Permission denied (publickey).
> 2024-04-06T11:49:23.0959539Z fatal: Could not read from remote repository.

<details><summary>raw log</summary>
```
2024-04-06T11:49:06.6583197Z Current runner version: '2.315.0'
2024-04-06T11:49:06.6606590Z ##[group]Operating System
2024-04-06T11:49:06.6607232Z Ubuntu
2024-04-06T11:49:06.6607667Z 22.04.4
2024-04-06T11:49:06.6608041Z LTS
2024-04-06T11:49:06.6608379Z ##[endgroup]
2024-04-06T11:49:06.6608865Z ##[group]Runner Image
2024-04-06T11:49:06.6609275Z Image: ubuntu-22.04
2024-04-06T11:49:06.6609679Z Version: 20240403.1.0
2024-04-06T11:49:06.6610764Z Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240403.1/images/ubuntu/Ubuntu2204-Readme.md
2024-04-06T11:49:06.6612208Z Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240403.1
2024-04-06T11:49:06.6613038Z ##[endgroup]
2024-04-06T11:49:06.6613538Z ##[group]Runner Image Provisioner
2024-04-06T11:49:06.6614022Z 2.0.361.1
2024-04-06T11:49:06.6614391Z ##[endgroup]
2024-04-06T11:49:06.6616561Z ##[group]GITHUB_TOKEN Permissions
2024-04-06T11:49:06.6618139Z Actions: read
2024-04-06T11:49:06.6619022Z Checks: read
2024-04-06T11:49:06.6619549Z Contents: write
2024-04-06T11:49:06.6620141Z Deployments: read
2024-04-06T11:49:06.6620545Z Discussions: read
2024-04-06T11:49:06.6620905Z Issues: read
2024-04-06T11:49:06.6621350Z Metadata: read
2024-04-06T11:49:06.6621761Z Packages: read
2024-04-06T11:49:06.6622205Z Pages: read
2024-04-06T11:49:06.6622555Z PullRequests: read
2024-04-06T11:49:06.6622989Z RepositoryProjects: read
2024-04-06T11:49:06.6623510Z SecurityEvents: read
2024-04-06T11:49:06.6623921Z Statuses: read
2024-04-06T11:49:06.6624279Z ##[endgroup]
2024-04-06T11:49:06.6627474Z Secret source: Actions
2024-04-06T11:49:06.6628074Z Prepare workflow directory
2024-04-06T11:49:06.7249864Z Prepare all required actions
2024-04-06T11:49:06.7405585Z Getting action download info
2024-04-06T11:49:06.8978882Z Download action repository 'JuliaRegistries/TagBot@v1' (SHA:aa5545ecce2ae3b2cd7d3a8a0a286ec6bf25838f)
2024-04-06T11:49:07.4348478Z Complete job name: TagBot
2024-04-06T11:49:07.5239692Z ##[group]Pull down action image 'ghcr.io/juliaregistries/tagbot:1.18.1'
2024-04-06T11:49:07.5328925Z ##[command]/usr/bin/docker pull ghcr.io/juliaregistries/tagbot:1.18.1
2024-04-06T11:49:08.0117367Z 1.18.1: Pulling from juliaregistries/tagbot
2024-04-06T11:49:08.0119057Z 578acb154839: Pulling fs layer
2024-04-06T11:49:08.0119916Z ac65017cfc56: Pulling fs layer
2024-04-06T11:49:08.0120568Z 100bb96a0327: Pulling fs layer
2024-04-06T11:49:08.0121037Z 2b7e5f1b5877: Pulling fs layer
2024-04-06T11:49:08.0121558Z 195da115a4ff: Pulling fs layer
2024-04-06T11:49:08.0122128Z 07da1ba67f9f: Pulling fs layer
2024-04-06T11:49:08.0122658Z 3e7cdb206ebc: Pulling fs layer
2024-04-06T11:49:08.0123106Z d486df036ef1: Pulling fs layer
2024-04-06T11:49:08.0123646Z 2c5859819217: Pulling fs layer
2024-04-06T11:49:08.0124144Z ab0f4693bd7c: Pulling fs layer
2024-04-06T11:49:08.0124620Z 2b7e5f1b5877: Waiting
2024-04-06T11:49:08.0125069Z 195da115a4ff: Waiting
2024-04-06T11:49:08.0125611Z 07da1ba67f9f: Waiting
2024-04-06T11:49:08.0126559Z 3e7cdb206ebc: Waiting
2024-04-06T11:49:08.0127526Z d486df036ef1: Waiting
2024-04-06T11:49:08.0128540Z 2c5859819217: Waiting
2024-04-06T11:49:08.0129558Z ab0f4693bd7c: Waiting
2024-04-06T11:49:08.1573922Z ac65017cfc56: Download complete
2024-04-06T11:49:08.2854433Z 578acb154839: Verifying Checksum
2024-04-06T11:49:08.2855500Z 578acb154839: Download complete
2024-04-06T11:49:08.2866436Z 2b7e5f1b5877: Verifying Checksum
2024-04-06T11:49:08.2867087Z 2b7e5f1b5877: Download complete
2024-04-06T11:49:08.4817991Z 100bb96a0327: Verifying Checksum
2024-04-06T11:49:08.4819171Z 100bb96a0327: Download complete
2024-04-06T11:49:08.5495291Z 195da115a4ff: Verifying Checksum
2024-04-06T11:49:08.5497010Z 195da115a4ff: Download complete
2024-04-06T11:49:08.6084748Z 3e7cdb206ebc: Verifying Checksum
2024-04-06T11:49:08.6089841Z 3e7cdb206ebc: Download complete
2024-04-06T11:49:08.7359841Z 2c5859819217: Verifying Checksum
2024-04-06T11:49:08.7369817Z 2c5859819217: Download complete
2024-04-06T11:49:08.8025373Z d486df036ef1: Verifying Checksum
2024-04-06T11:49:08.8028030Z d486df036ef1: Download complete
2024-04-06T11:49:08.8531599Z 07da1ba67f9f: Verifying Checksum
2024-04-06T11:49:08.8532904Z 07da1ba67f9f: Download complete
2024-04-06T11:49:08.8551497Z ab0f4693bd7c: Verifying Checksum
2024-04-06T11:49:08.8553273Z ab0f4693bd7c: Download complete
2024-04-06T11:49:09.5279580Z 578acb154839: Pull complete
2024-04-06T11:49:11.5722590Z ac65017cfc56: Pull complete
2024-04-06T11:49:12.0603946Z 100bb96a0327: Pull complete
2024-04-06T11:49:12.0697042Z 2b7e5f1b5877: Pull complete
2024-04-06T11:49:12.3070722Z 195da115a4ff: Pull complete
2024-04-06T11:49:13.5922417Z 07da1ba67f9f: Pull complete
2024-04-06T11:49:13.6870581Z 3e7cdb206ebc: Pull complete
2024-04-06T11:49:14.5152648Z d486df036ef1: Pull complete
2024-04-06T11:49:14.5252970Z 2c5859819217: Pull complete
2024-04-06T11:49:14.5387378Z ab0f4693bd7c: Pull complete
2024-04-06T11:49:14.5425103Z Digest: sha256:695dd266972fa0effdacc231e38bf48d742a41c39281e801d32dce4fbb7e0d45
2024-04-06T11:49:14.5438464Z Status: Downloaded newer image for ghcr.io/juliaregistries/tagbot:1.18.1
2024-04-06T11:49:14.5448425Z ghcr.io/juliaregistries/tagbot:1.18.1
2024-04-06T11:49:14.5476788Z ##[endgroup]
2024-04-06T11:49:14.5890386Z ##[group]Run JuliaRegistries/TagBot@v1
2024-04-06T11:49:14.5890901Z with:
2024-04-06T11:49:14.5891645Z   token: ***
2024-04-06T11:49:14.6052962Z   ssh: ***
2024-04-06T11:49:14.6053325Z   registry: JuliaRegistries/General
2024-04-06T11:49:14.6053872Z   github: github.com
2024-04-06T11:49:14.6054243Z   github_api: api.github.com
2024-04-06T11:49:14.6054643Z   branches: false
2024-04-06T11:49:14.6055001Z   dispatch: false
2024-04-06T11:49:14.6055332Z   dispatch_delay: 5
2024-04-06T11:49:14.6055683Z   lookback: 3
2024-04-06T11:49:14.6056065Z   draft: false
2024-04-06T11:49:14.6056371Z   user: github-actions[bot]
2024-04-06T11:49:14.6056880Z   email: 41898282+github-actions[bot]@users.noreply.github.com
2024-04-06T11:49:14.6059197Z   changelog: ## {{ package }} {{ version }}

{% if previous_release %}
[Diff since {{ previous_release }}]({{ compare_url }})
{% endif %}

{% if custom %}
{{ custom }}
{% endif %}

{% if pulls %}
**Merged pull requests:**
{% for pull in pulls %}
- {{ pull.title }} (#{{ pull.number }}) (@{{ pull.author.username }})
{% endfor %}

{% if issues %}
**Closed issues:**
{% for issue in issues %}
- {{ issue.title }} (#{{ issue.number }})
{% endfor %}
{% endif %}
{% endif %}

2024-04-06T11:49:14.6060991Z ##[endgroup]
2024-04-06T11:49:14.6485896Z ##[command]/usr/bin/docker run --name ghcriojuliaregistriestagbot1181_919d2e --label 7bc2dc --workdir /github/workspace --rm -e "INPUT_TOKEN" -e "INPUT_SSH" -e "INPUT_REGISTRY" -e "INPUT_GITHUB" -e "INPUT_GITHUB_API" -e "INPUT_BRANCHES" -e "INPUT_DISPATCH" -e "INPUT_DISPATCH_DELAY" -e "INPUT_LOOKBACK" -e "INPUT_SSH_PASSWORD" -e "INPUT_GPG" -e "INPUT_GPG_PASSWORD" -e "INPUT_REGISTRY_SSH" -e "INPUT_DRAFT" -e "INPUT_USER" -e "INPUT_EMAIL" -e "INPUT_BRANCH" -e "INPUT_SUBDIR" -e "INPUT_TAG_PREFIX" -e "INPUT_CHANGELOG" -e "INPUT_CHANGELOG_IGNORE" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/ColorTypes.jl/ColorTypes.jl":"/github/workspace" ghcr.io/juliaregistries/tagbot:1.18.1
2024-04-06T11:49:18.8221013Z Processing version v0.11.5 (465277a63829fbddfd9843336ef115751d5dae59)
2024-04-06T11:49:18.9422853Z Generating changelog for version v0.11.5 (465277a63829fbddfd9843336ef115751d5dae59)
2024-04-06T11:49:23.0956857Z git@github.com: Permission denied (publickey).
2024-04-06T11:49:23.0959539Z fatal: Could not read from remote repository.
2024-04-06T11:49:23.0960199Z 
2024-04-06T11:49:23.1024963Z Traceback (most recent call last):
2024-04-06T11:49:23.1026457Z   File "/root/tagbot/action/__main__.py", line 96, in <module>
2024-04-06T11:49:23.1027314Z     repo.create_release(version, sha)
2024-04-06T11:49:23.1028206Z   File "/root/tagbot/action/repo.py", line 595, in create_release
2024-04-06T11:49:23.1029134Z     self._git.create_tag(version_tag, sha, log)
2024-04-06T11:49:23.1030380Z   File "/root/tagbot/action/git.py", line 107, in create_tag
2024-04-06T11:49:23.1031355Z     self.command("push", "origin", version)
2024-04-06T11:49:23.1032203Z   File "/root/tagbot/action/git.py", line 71, in command
2024-04-06T11:49:23.1033319Z     raise Abort(f"Git command '{cmd}' failed")
2024-04-06T11:49:23.1034633Z tagbot.action.Abort: Git command 'git -C /tmp/tagbot_repo_awxoje85 push origin v0.11.5' failed
2024-04-06T11:49:23.1035454Z 
2024-04-06T11:49:23.1035910Z During handling of the above exception, another exception occurred:
2024-04-06T11:49:23.1036518Z 
2024-04-06T11:49:23.1036875Z Traceback (most recent call last):
2024-04-06T11:49:23.1037735Z   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2024-04-06T11:49:23.1038694Z     return _run_code(code, main_globals, None,
2024-04-06T11:49:23.1039633Z   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
2024-04-06T11:49:23.1040463Z     exec(code, run_globals)
2024-04-06T11:49:23.1041131Z   File "/root/tagbot/action/__main__.py", line 99, in <module>
2024-04-06T11:49:23.1041988Z     repo.handle_error(e)
2024-04-06T11:49:23.1042702Z   File "/root/tagbot/action/repo.py", line 645, in handle_error
2024-04-06T11:49:23.1043594Z     raise Abort("Cannot continue due to internal failure")
2024-04-06T11:49:23.1044524Z tagbot.action.Abort: Cannot continue due to internal failure
2024-04-06T11:49:23.1045430Z Please make sure you have the correct access rights
2024-04-06T11:49:23.1046148Z and the repository exists.
2024-04-06T11:49:23.1078614Z ##[error]TagBot experienced an unexpected internal failure
2024-04-06T11:49:23.1088137Z Traceback (most recent call last):
2024-04-06T11:49:23.1089028Z   File "/root/tagbot/action/__main__.py", line 96, in <module>
2024-04-06T11:49:23.1089846Z     repo.create_release(version, sha)
2024-04-06T11:49:23.1092337Z   File "/root/tagbot/action/repo.py", line 595, in create_release
2024-04-06T11:49:23.1093225Z     self._git.create_tag(version_tag, sha, log)
2024-04-06T11:49:23.1094192Z   File "/root/tagbot/action/git.py", line 107, in create_tag
2024-04-06T11:49:23.1094998Z     self.command("push", "origin", version)
2024-04-06T11:49:23.1095761Z   File "/root/tagbot/action/git.py", line 71, in command
2024-04-06T11:49:23.1096693Z     raise Abort(f"Git command '{cmd}' failed")
2024-04-06T11:49:23.1097870Z tagbot.action.Abort: Git command 'git -C /tmp/tagbot_repo_awxoje85 push origin v0.11.5' failed
2024-04-06T11:49:23.1098869Z 
2024-04-06T11:49:23.1100721Z ##[error]Issue reporting failed
2024-04-06T11:49:23.1102238Z Traceback (most recent call last):
2024-04-06T11:49:23.1102981Z   File "/root/tagbot/action/__main__.py", line 96, in <module>
2024-04-06T11:49:23.1103874Z     repo.create_release(version, sha)
2024-04-06T11:49:23.1104693Z   File "/root/tagbot/action/repo.py", line 595, in create_release
2024-04-06T11:49:23.1105553Z     self._git.create_tag(version_tag, sha, log)
2024-04-06T11:49:23.1106830Z   File "/root/tagbot/action/git.py", line 107, in create_tag
2024-04-06T11:49:23.1107640Z     self.command("push", "origin", version)
2024-04-06T11:49:23.1108404Z   File "/root/tagbot/action/git.py", line 71, in command
2024-04-06T11:49:23.1109390Z     raise Abort(f"Git command '{cmd}' failed")
2024-04-06T11:49:23.1110531Z tagbot.action.Abort: Git command 'git -C /tmp/tagbot_repo_awxoje85 push origin v0.11.5' failed
2024-04-06T11:49:23.1111356Z 
2024-04-06T11:49:23.1111767Z During handling of the above exception, another exception occurred:
2024-04-06T11:49:23.1112535Z 
2024-04-06T11:49:23.1112745Z Traceback (most recent call last):
2024-04-06T11:49:23.1113985Z   File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
2024-04-06T11:49:23.1115253Z     return self.version(api_version=False)["ApiVersion"]
2024-04-06T11:49:23.1116505Z   File "/usr/local/lib/python3.8/site-packages/docker/api/daemon.py", line 181, in version
2024-04-06T11:49:23.1117578Z     return self._result(self._get(url), json=True)
2024-04-06T11:49:23.1119004Z   File "/usr/local/lib/python3.8/site-packages/docker/utils/decorators.py", line 46, in inner
2024-04-06T11:49:23.1120178Z     return f(self, *args, **kwargs)
2024-04-06T11:49:23.1121180Z   File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 237, in _get
2024-04-06T11:49:23.1122284Z     return self.get(url, **self._set_request_timeout(kwargs))
2024-04-06T11:49:23.1123572Z   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 602, in get
2024-04-06T11:49:23.1124625Z     return self.request("GET", url, **kwargs)
2024-04-06T11:49:23.1125715Z   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
2024-04-06T11:49:23.1126850Z     resp = self.send(prep, **send_kwargs)
2024-04-06T11:49:23.1127947Z   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
2024-04-06T11:49:23.1129995Z     r = adapter.send(request, **kwargs)
2024-04-06T11:49:23.1131168Z   File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
2024-04-06T11:49:23.1132127Z     resp = conn.urlopen(
2024-04-06T11:49:23.1133307Z   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 791, in urlopen
2024-04-06T11:49:23.1134369Z     response = self._make_request(
2024-04-06T11:49:23.1135565Z   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 497, in _make_request
2024-04-06T11:49:23.1136728Z     conn.request(
2024-04-06T11:49:23.1137469Z TypeError: request() got an unexpected keyword argument 'chunked'
2024-04-06T11:49:23.1138104Z 
2024-04-06T11:49:23.1138688Z During handling of the above exception, another exception occurred:
2024-04-06T11:49:23.1139457Z 
2024-04-06T11:49:23.1139667Z Traceback (most recent call last):
2024-04-06T11:49:23.1140436Z   File "/root/tagbot/action/repo.py", line 640, in handle_error
2024-04-06T11:49:23.1141213Z     self._report_error(trace)
2024-04-06T11:49:23.1142022Z   File "/root/tagbot/action/repo.py", line 442, in _report_error
2024-04-06T11:49:23.1142805Z     "image": self._image_id(),
2024-04-06T11:49:23.1143502Z   File "/root/tagbot/action/repo.py", line 431, in _image_id
2024-04-06T11:49:23.1144348Z     client = docker.from_env()
2024-04-06T11:49:23.1145365Z   File "/usr/local/lib/python3.8/site-packages/docker/client.py", line 96, in from_env
2024-04-06T11:49:23.1146291Z     return cls(
2024-04-06T11:49:23.1147314Z   File "/usr/local/lib/python3.8/site-packages/docker/client.py", line 45, in __init__
2024-04-06T11:49:23.1148264Z     self.api = APIClient(*args, **kwargs)
2024-04-06T11:49:23.1149306Z   File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 197, in __init__
2024-04-06T11:49:23.1150466Z     self._version = self._retrieve_server_version()
2024-04-06T11:49:23.1151717Z   File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
2024-04-06T11:49:23.1152921Z     raise DockerException(
2024-04-06T11:49:23.1154451Z docker.errors.DockerException: Error while fetching server API version: request() got an unexpected keyword argument 'chunked'
2024-04-06T11:49:23.1155497Z 
2024-04-06T11:49:23.3432127Z Cleaning up orphan processes
```
</details>
